services:
  mongo:
    image: mongo:7
    container_name: generator-mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: generator-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  rabbitmq-setup:
    build:
      context: ..
      dockerfile: docker/dockerfile
    command: ["python","-m", "rabbitmq.rabbitmqSetup"]
    environment:
      RABBITMQ_HOST: rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy

  consumer:
    build:
      context: ..
      dockerfile: docker/dockerfile
    develop:
      watch:
        - action: sync+restart
          path: ../app
          target: /app/app
        - action: sync+restart
          path: ../rabbitmq
          target: /app/rabbitmq
        - action: sync+restart
          path: ../buildersUtils
          target: /app/buildersUtils

    environment:
      MONGODB_URI: mongodb://mongo:27017/
      RABBITMQ_HOST: rabbitmq
    depends_on:
      mongo:
        condition: service_started
      rabbitmq-setup:
        condition: service_completed_successfully
    restart: unless-stopped

  app:
    build:
      context: ..
      dockerfile: docker/dockerfile
    develop:
      watch:
        - action: sync+restart
          path: ../app
          target: /app/app
        - action: sync+restart
          path: ../buildersUtils
          target: /app/buildersUtils
    command: ["python","-m","app.app"]
    ports:
      - "8000:8000"
    environment:
      MONGODB_URI: mongodb://mongo:27017/
      RABBITMQ_HOST: rabbitmq
    depends_on:
      mongo:
        condition: service_started
      rabbitmq-setup:
        condition: service_completed_successfully
    restart: unless-stopped 
    
volumes:
  mongo-data:
    external: true
