FROM python:3.12.3-slim

WORKDIR /app

COPY app/ ./app/
COPY rabbitmq/ ./rabbitmq/
COPY buildersUtils/ ./buildersUtils/

RUN pip install pika
RUN pip install pymongo
RUN pip install dotenv
RUN pip install fastapi
RUN pip install uvicorn

ENV PYTHONUNBUFFERED=1

CMD ["python","-m","rabbitmq.consumer"]